[package]
name = "qrsa"
version = "0.1.0"
edition = "2021"
description = "Quauntum Repeater Software Architecture"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
