[workspace]
members = [
    "bootstrap",
    "connection_manager",
    "hardware_monitor",
    "rule_engine",
    "routing_daemon",
    "realtime_controller"
]

# https://doc.rust-lang.org/cargo/reference/resolver.html#feature-resolver-version-2
resolver = "2"
