version: '3.9'

services:
  controller:
    build:
      context: ./qrsa_prototype
      dockerfile: ../controller/Dockerfile
    working_dir: /usr/app
    command: rye run python src/app/server.py
    volumes:
      - ./qrsa_prototype:/usr/app/:rw
    ports:
      - 8080
    networks:
      qrsa_net:
        ipv4_address: 172.18.0.254
  qnode1:
    build: ./qnode
    command: rye run python src/app/server.py
    working_dir: /usr/app
    volumes:
      - ./qrsa_prototype:/usr/app/:rw
    ports:
      - 8080
    depends_on:
      - controller
    networks:
      qrsa_net:
        ipv4_address: 172.18.0.2
  qnode2:
    build: ./qnode
    command: rye run python src/app/server.py
    working_dir: /usr/app
    ports:
      - 8080
    depends_on:
      - controller
    networks:
      qrsa_net:
        ipv4_address: 172.18.0.3
    volumes:
      - ./qrsa_prototype:/usr/app/:rw

  
networks:
  qrsa_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/24