version: '3.9'

services:
  controller:
    command: tail -f /dev/null
    working_dir: /usr/app
    volumes:
      - ./qrsa_prototype:/usr/app/:rw
      - ./logs:/usr/app/logs:rw
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - ./docker-compose.yml:/usr/app/docker-compose.yml:ro
    build: ./controller
    ports:
      - 9002:9002
    networks:
      - global
  qnode1:
    command: python server.py
    working_dir: /usr/app
    volumes:
      - ./qrsa_prototype:/usr/app/:rw
      - ./logs:/usr/app/logs:rw
    build: ./qnode
    ports:
      - 8080
    networks:
      - global
  qnode2:
    command: python server.py
    working_dir: /usr/app
    build: ./qnode
    ports:
      - 8080
    networks:
      - global
    volumes:
      - ./qrsa_prototype:/usr/app/:rw
      - ./logs:/usr/app/logs:rw

  
networks:
  global:
    driver: bridge