version: '3.9'

services:
  controller:
    build: ./controller
    entrypoint: sh .entrypoints/.controller_entrypoint.sh
    working_dir: /usr/app
    volumes:
      - ./qrsa_prototype:/usr/app/:rw
      - /usr/app/.venv # Not to share .venv over the multiple containers
      - ./logs:/usr/app/logs:rw
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - ./docker-compose.yml:/usr/app/docker-compose.yml:ro
    ports:
      - 8080
    networks:
      qrsa_net:
        ipv4_address: 172.18.0.254
  qnode1:
    build: ./qnode
    entrypoint: sh .entrypoints/.qnode_entrypoint.sh
    working_dir: /usr/app
    volumes:
      - ./qrsa_prototype:/usr/app/:rw
      - /usr/app/.venv
      - ./logs:/usr/app/logs:rw
    ports:
      - 8080
    networks:
      qrsa_net:
        ipv4_address: 172.18.0.2
  qnode2:
    build: ./qnode
    entrypoint: sh .entrypoints/.qnode_entrypoint.sh
    working_dir: /usr/app
    ports:
      - 8080
    networks:
      qrsa_net:
        ipv4_address: 172.18.0.3
    volumes:
      - ./qrsa_prototype:/usr/app/:rw
      - /usr/app/.venv
      - ./logs:/usr/app/logs:rw

  
networks:
  qrsa_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/24