version: '3.9'

services:
  controller:
    command: rye run python server.py
    working_dir: /usr/app
    volumes:
      - ./qrsa_prototype:/usr/app/:rw
    build: ./controller
    ports:
      - 8080
    networks:
      qrsa_net:
        ipv4_address: 172.18.0.254
  qnode1:
    command: rye run python server.py
    working_dir: /usr/app
    volumes:
      - ./qrsa_prototype:/usr/app/:rw
    build: ./qnode
    ports:
      - 8080
    networks:
      qrsa_net:
        ipv4_address: 172.18.0.2
  qnode2:
    command: rye run python server.py
    working_dir: /usr/app
    build: ./qnode
    ports:
      - 8080
    networks:
      qrsa_net:
        ipv4_address: 172.18.0.3
    volumes:
      - ./qrsa_prototype:/usr/app/:rw

  
networks:
  qrsa_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/24