name: Document generation test

on: [push, pull_request]

jobs:
    doc_test:
        name: generate document
        runs-on: ubuntu-latest
        steps:
            - name: Checkout respository
              uses: actions/checkout@v3
            - name: Generate document
              uses: actions-rs/cargo@v1
              with:
                command: doc
            


