name: ci

on: [push, pull_request]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build base image
        uses: docker/build-push-action@v4
        with:
          context: "{{defaultContext}}:qrsa_prototype"
          target: base
          push: false
          tags: qrsa_prototype/base:latest
      -
        name: Build controller image
        uses: docker/build-push-action@v4
        with:
          context: "{{defaultContext}}:qrsa_prototype"
          target: controller 
          push: false
          tags: qrsa_prototype/controller:latest
  pytest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Rye
        uses: baptiste0928/cargo-install@v2
        with:
          crate: rye
          git: https://github.com/mitsuhiko/rye
          branch: main
      - name: Setup Rye
        working-directory: qrsa_prototype
        run: rye sync
      - name: Run tests
        working-directory: qrsa_prototype
        run: rye run pytest --cov --cov-report=xml
      - name: Upload coverage
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
  
