name: ci

on: [push, pull_request]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build base image
        uses: docker/build-push-action@v4
        with:
          context: "{{defaultContext}}:qrsa_prototype"
          target: base
          push: false
          tags: qrsa_prototype/base:latest
      -
        name: Build controller image
        uses: docker/build-push-action@v4
        with:
          context: "{{defaultContext}}:qrsa_prototype"
          target: controller 
          push: false
          tags: qrsa_prototype/controller:latest