name: ci

on: [push, pull_request]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build base image
        uses: docker/build-push-action@v4
        with:
          context: "{{defaultContext}}:qrsa_prototype"
          target: base
          push: false
          tags: qrsa_prototype/base:latest
      -
        name: Build controller image
        uses: docker/build-push-action@v4
        with:
          context: "{{defaultContext}}:qrsa_prototype"
          target: controller 
          push: false
          tags: qrsa_prototype/controller:latest
  pytest:
    runs-on: ubuntu-latest
    steps:
      - name: Up containers
        run: ls && docker-compose up -d --build
      - name: Enter container
        run: docker exec -it qrsa-qnode1-1 bash
      - name: Setup Rye
        run: rye sync -f --no-lock
      - name: Run tests
        run: rye run pytest --cov --cov-report=xml
      - name: Upload to codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
